services:
  db:
    image: mysql:8.1.0
    command: --innodb-buffer-pool-size=5M --innodb-log-buffer-size=256K --key-buffer-size=8 --thread-cache-size=0 --host-cache-size=0 --innodb-ft-cache-size=1600000 --innodb-ft-total-cache-size=32000000 --performance-schema=off --thread-stack=131072 --sort-buffer-size=32K --read-buffer-size=8200 --read-rnd-buffer-size=8200 --max-heap-table-size=16K --tmp-table-size=1K --bulk-insert-buffer-size=0 --join-buffer-size=128 --net-buffer-length=1K --innodb-sort-buffer-size=64K --binlog-cache-size=4K --binlog-stmt-cache-size=4K
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env

  server:
    build:
      context: .
      network: 'host'
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
    links:
      - db

volumes:
  db-volume:
